Repository qbicsoftware/spring-boot-rest-service-template, pull requests merged in 2022-02, with the labels that each got.

#9 CI: Adds auto-label Github workflow
  .github/pr-labels.yml
  .github/workflows/label-pull-requests.yml
Labels: feature

#11 Create PR with version change to main
  .github/workflows/create-release.yml
Labels: chore

#13 Add Spring Framework Apache 2.0 reference
  README.md
Labels: chore

#15 Exclude github-actions Contributions from Changelog
  .github/release.yml
Labels: chore

#17 Rename actions jobs
  .github/workflows/build_package.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-release.yml
  .github/workflows/label-pull-requests.yml
  .github/workflows/nexus-publish-snapshots.yml
  .github/workflows/run_tests.yml
Labels: chore

#19 Use Johnny's Github token instead of the action token
  .github/workflows/create-release.yml
Labels: fix

#21 Pushes after the remote branch has been created
  .github/workflows/create-release.yml
Labels: fix

#27 Introduces PR triggers for package and test workflow
  .github/workflows/build_package.yml
  .github/workflows/run_tests.yml
Labels: fix
